#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#	Copyright (c) 1987  Intel Corporation
#	All Rights Rreserved
#
#	INTEL CORPORATION PROPRIETARY INFORMATION
#
#	This software is supplied to AT & T under the terms of a license 
#	agreement with Intel Corporation and may not be copied nor 
#	disclosed except in accordance with the terms of that agreement.

#ident	"@(#)mbus:cmd/ckperms/ckperms.mk	1.3"

#	Makefile for ckperms  mkperms

ROOT =

DIR = $(ROOT)/sbin

INC = $(ROOT)/usr/include

LDFLAGS = -s

CFLAGS = -O -I$(INC) -DPORTAR

STRIP = strip

SIZE = size


#top#
# Generated by makefile 1.47

MAKEFILE = ckperms.mk


MAINS = ckperms mkperms

OBJECTS =  ckperms.o mcsubr.o mkperms.o

SOURCES =  ckperms.c mcsubr.c mkperms.c 

ALL:		$(MAINS)

ckperms:	ckperms.o mcsubr.o
	$(CC) $(CFLAGS)  -o ckperms  ckperms.o mcsubr.o   $(LDFLAGS) $(SHLIBS)

mkperms:	mkperms.o mcsubr.o
	$(CC) $(CFLAGS)  -o mkperms  mkperms.o mcsubr.o   $(LDFLAGS) $(SHLIBS)


ckperms.o:	 $(INC)/stdio.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h 

mkperms.o:	 $(INC)/stdio.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h 

mcsubr.o:	 $(INC)/stdio.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h 

GLOBALINCS = $(INC)/stdio.h $(INC)/sys/stat.h \
	$(INC)/sys/types.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset ckperms $(DIR) 0755 root sys
	cpset mkperms $(DIR) 0755 root sys

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
