#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)localedef:montbl/montbl.mk	1.1.3.1"

#	Makefile for montbl

ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

INS = install

INSDIR = $(ROOT)/usr/bin

#top#
# Generated by makefile 1.1

MAKEFILE = montbl.mk


MAINS = montbl

OBJECTS =  montbl.o

SOURCES =  montbl.c

ALL:		$(MAINS)

montbl:		montbl.o 
	$(CC) $(CFLAGS)  -o montbl  montbl.o   $(LDFLAGS)


montbl.o:	 $(INC)/ctype.h $(INC)/limits.h \
		 $(INC)/locale.h $(INC)/stdio.h \
		 $(INC)/stdlib.h $(INC)/string.h 

GLOBALINCS = $(INC)/ctype.h $(INC)/limits.h \
	$(INC)/locale.h $(INC)/stdio.h $(INC)/stdlib.h \
	$(INC)/string.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(INSDIR) montbl ;\
	$(INS) -f $(ROOT)/usr/lib/locale/C montbl_C ;\
	$(CH)./montbl montbl_C ;\
	$(CH)install -f $(ROOT)/usr/lib/locale/C LC_MONETARY ;\
	$(CH)rm -f LC_MONETARY

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
