/*	Copyright (c) 1990 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/


#ident	"@(#)lp:lib/lpNet/xdrMsgs.c	1.2.2.1"
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "xdrMsgs.h"
#define	MSGS_VERSION_MAJOR	1
#define	MSGS_VERSION_MINOR	1

bool_t
xdr_networkMsgType(xdrs, objp)
	XDR *xdrs;
	networkMsgType *objp;
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_jobControlCode(xdrs, objp)
	XDR *xdrs;
	jobControlCode *objp;
{
	if (!xdr_enum(xdrs, (enum_t *)objp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_routingControl(xdrs, objp)
	XDR *xdrs;
	routingControl *objp;
{
	if (!xdr_u_int(xdrs, &objp->sysId)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->msgId)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_jobControl(xdrs, objp)
	XDR *xdrs;
	jobControl *objp;
{
	if (!xdr_u_char(xdrs, &objp->controlCode)) {
		return (FALSE);
	}
	if (!xdr_u_char(xdrs, &objp->priority)) {
		return (FALSE);
	}
	if (!xdr_u_char(xdrs, &objp->endOfJob)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->jobId)) {
		return (FALSE);
	}
	if (!xdr_long(xdrs, &objp->timeStamp)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_networkMsgTag(xdrs, objp)
	XDR *xdrs;
	networkMsgTag *objp;
{
	if (!xdr_u_char(xdrs, &objp->versionMajor)) {
		return (FALSE);
	}
	if (!xdr_u_char(xdrs, &objp->versionMinor)) {
		return (FALSE);
	}
	if (!xdr_routingControl(xdrs, &objp->routeControl)) {
		return (FALSE);
	}
	if (!xdr_networkMsgType(xdrs, &objp->msgType)) {
		return (FALSE);
	}
	if (!xdr_pointer(xdrs, (char **)&objp->jobControlp, sizeof(jobControl), xdr_jobControl)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_systemIdMsg(xdrs, objp)
	XDR *xdrs;
	systemIdMsg *objp;
{
	if (!xdr_string(xdrs, &objp->systemNamep, ~0)) {
		return (FALSE);
	}
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_dataPacketMsg(xdrs, objp)
	XDR *xdrs;
	dataPacketMsg *objp;
{
	if (!xdr_int(xdrs, &objp->endOfPacket)) {
		return (FALSE);
	}
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_packetBundleMsg(xdrs, objp)
	XDR *xdrs;
	packetBundleMsg *objp;
{
	if (!xdr_array(xdrs, (char **)&objp->packets.packets_val, (u_int *)&objp->packets.packets_len, ~0, sizeof(dataPacketMsg), xdr_dataPacketMsg)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_fileFragmentMsg(xdrs, objp)
	XDR *xdrs;
	fileFragmentMsg *objp;
{
	if (!xdr_int(xdrs, &objp->endOfFile)) {
		return (FALSE);
	}
	if (!xdr_long(xdrs, &objp->sizeOfFile)) {
		return (FALSE);
	}
	if (!xdr_string(xdrs, &objp->destPathp, ~0)) {
		return (FALSE);
	}
	if (!xdr_bytes(xdrs, (char **)&objp->fragment.fragment_val, (u_int *)&objp->fragment.fragment_len, ~0)) {
		return (FALSE);
	}
	return (TRUE);
}
