#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)mkmsgs:mkmsgs.mk	1.6.4.1"

#	Makefile for mkmsgs

ROOT =

INS = install

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s -lgen $(SHLIBS)

CFLAGS = -O -I$(INC) 

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = mkmsgs.mk


MAINS = mkmsgs

OBJECTS =  mkmsgs.o

SOURCES =  mkmsgs.c

ALL:		$(MAINS)

mkmsgs:		mkmsgs.o 
	$(CC) $(CFLAGS)  -o mkmsgs  mkmsgs.o   $(LDFLAGS)


mkmsgs.o:		 $(INC)/stdio.h $(INC)/string.h $(INC)/sys/types.h \
		 $(INC)/sys/stat.h $(INC)/signal.h

GLOBALINCS = $(INC)/stdio.h $(INC)/sys/types.h $(INC)/sys/stat.h\
		$(INC)/string.h $(INC)/signal.h

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f  $(DIR) -m 0555 -u root -g root $(MAINS)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
