#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)libgenIO:libgenIO.mk	1.3.1.1"

# Generated by makefile 1.47

MAKEFILE = libgenIO.mk

USRLIB=$(ROOT)/usr/lib

INC=$(ROOT)/usr/include

INCSYS=$(ROOT)/usr/include

INS=install

LIBRARY = libgenIO.a

OBJECTS =  g_init.o g_read.o g_write.o

SOURCES =  g_init.c g_read.c g_write.c

ALL:		$(LIBRARY)

$(LIBRARY):	$(LIBRARY)(g_write.o) $(LIBRARY)(g_read.o) \
		$(LIBRARY)(g_init.o) 


$(LIBRARY)(g_init.o):	 $(INC)/errno.h \
		 $(INCSYS)/sys/errno.h $(INCSYS)/sys/types.h \
		 $(INCSYS)/sys/stat.h $(INC)/fcntl.h \
		 $(INCSYS)/sys/fcntl.h \
		 $(INC)/stdio.h $(INC)/string.h \
		 $(INC)/ftw.h $(INC)/libgenIO.h  $(INCSYS)/sys/mkdev.h

$(LIBRARY)(g_read.o):	 $(INC)/errno.h \
		 $(INCSYS)/sys/errno.h $(INC)/libgenIO.h 

$(LIBRARY)(g_write.o):	 $(INC)/errno.h \
		 $(INCSYS)/sys/errno.h $(INC)/libgenIO.h 

GLOBALINCS = $(INC)/errno.h $(INC)/fcntl.h $(INC)/ftw.h \
	$(INC)/stdio.h $(INC)/string.h $(INCSYS)/sys/errno.h \
	$(INCSYS)/sys/fcntl.h $(INCSYS)/sys/stat.h \
	$(INCSYS)/sys/types.h 

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(LIBRARY)

install: ALL
	$(INS) -f $(USRLIB) -m 644 $(LIBRARY)
