/*	Copyright (c) 1990 UNIX System Laboratories, Inc.	*/
/*	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T	*/
/*	  All Rights Reserved  	*/

/*	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF     	*/
/*	UNIX System Laboratories, Inc.                     	*/
/*	The copyright notice above does not evidence any   	*/
/*	actual or intended publication of such source code.	*/


#ident	"@(#)librpcsvc:sprayxdr.c	1.2.2.1"

/*+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*	PROPRIETARY NOTICE (Combined)
*
* This source code is unpublished proprietary information
* constituting, or derived under license from AT&T's UNIX(r) System V.
* In addition, portions of such source code were derived from Berkeley
* 4.3 BSD under license from the Regents of the University of
* California.
*
*
*
*	Copyright Notice 
*
* Notice of copyright on this source code product does not indicate 
*  publication.
*
*	(c) 1986,1987,1988.1989  Sun Microsystems, Inc
*	(c) 1983,1984,1985,1986,1987,1988,1989  AT&T.
*          All rights reserved.
*/ 
#if !defined(lint) && defined(SCCSIDS)
static char sccsid[] = "@(#)sprayxdr.c 1.4 89/03/24 Copyr 1989 Sun Micro";
#endif

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include <rpcsvc/spray.h>

bool_t
xdr_spraytimeval(xdrs, objp)
	XDR *xdrs;
	spraytimeval *objp;
{
	if (!xdr_u_int(xdrs, &objp->sec)) {
		return (FALSE);
	}
	if (!xdr_u_int(xdrs, &objp->usec)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_spraycumul(xdrs, objp)
	XDR *xdrs;
	spraycumul *objp;
{
	if (!xdr_u_int(xdrs, &objp->counter)) {
		return (FALSE);
	}
	if (!xdr_spraytimeval(xdrs, &objp->clock)) {
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_sprayarr(xdrs, objp)
	XDR *xdrs;
	sprayarr *objp;
{
	if (!xdr_bytes(xdrs, (char **)&objp->sprayarr_val, (u_int *)&objp->sprayarr_len, SPRAYMAX)) {
		return (FALSE);
	}
	return (TRUE);
}
