#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.



#ident	"@(#)mkfifo:mkfifo.mk	1.1.1.1"

#	Makefile for mkfifo

ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(SHLIBS)

CFLAGS = -O -I$(INC) 

STRIP = strip

SIZE = size

INS = install

#top#
# Generated by makefile 1.47

MAKEFILE = mkfifo.mk


MAINS = mkfifo

OBJECTS =  mkfifo.o

SOURCES =  mkfifo.c

ALL:		$(MAINS)

mkfifo:		mkfifo.o 
	$(CC) $(CFLAGS)  -o mkfifo  mkfifo.o   $(LDFLAGS)


mkfifo.o:    $(INC)/stdio.h $(INC)/errno.h $(INC)/string.h \
		$(INC)/sys/types.h $(INC)/sys/stat.h

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) $(MAINS)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
