#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)touch:touch.mk	1.12.1.1"

#	Makefile for touch 

ROOT =

DIR = $(ROOT)/usr/bin

LINK = $(ROOT)/etc/link

INS = install

INC = $(ROOT)/usr/include

LDFLAGS = -s -lcmd -lgen $(PERFLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = touch.mk


MAINS = touch

OBJECTS =  touch.o

SOURCES =  touch.c

ALL:		$(MAINS)

touch:		touch.o	
	$(CC) $(CFLAGS)  -o touch  touch.o   $(LDFLAGS)


touch.o:	 $(INC)/stdio.h $(INC)/ctype.h \
		 $(INC)/sys/types.h $(INC)/sys/stat.h \
		 $(INC)/pwd.h $(INC)/time.h	$(INC)/unistd.h

GLOBALINCS = $(INC)/ctype.h $(INC)/pwd.h $(INC)/stdio.h \
	$(INC)/sys/stat.h $(INC)/sys/types.h $(INC)/time.h \
		 $(INC)/pwd.h $(INC)/time.h	$(INC)/unistd.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) -m 00555 -u bin -g bin touch
	-rm -f $(DIR)/settime
	ln -f $(DIR)/touch $(DIR)/settime

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
