#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)setuname:setuname.mk	1.2.1.1"

#makefile for setuname
ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s -lelf

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.2

MAKEFILE = setuname.mk

MAINS = setuname

OBJECTS =  setuname.o

SOURCES =  setuname.c

ALL:		 $(MAINS)

setuname:		setuname.o
	$(CC) $(CFLAGS) -o setuname setuname.o $(LDFLAGS) $(SHLIBS)



setuname.o:	 $(INC)/ctype.h $(INC)/errno.h \
		 $(INC)/signal.h $(INC)/stdio.h \
		 $(INC)/string.h $(INC)/sys/fcntl.h	\
		 $(INC)/sys/signal.h $(INC)/unistd.h 

GLOBALINCS = $(INC)/ctype.h $(INC)/errno.h $(INC)/signal.h \
	$(INC)/stdio.h $(INC)/string.h $(INC)/sys/fcntl.h \
	$(INC)/sys/signal.h $(INC)/unistd.h 


clean:
	rm -f $(OBJECTS)

clobber:	clean
	rm -f $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE) 
#bottom#

all : ALL

install: ALL
	install -f $(DIR) -m 00555 -u bin -g bin setuname	

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
