#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#	Portions Copyright (c) 1988, Sun Microsystems, Inc.
#	All Rights Reserved.


#ident	"@(#)chmod:chmod.mk	1.8.1.1"

#	Makefile for chmod 

ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include
INCSYS = $(ROOT)/usr/include

INS = install

LDFLAGS = -s

CFLAGS = -O -I$(INC) -I$(INCSYS)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = chmod.mk


MAINS = chmod

OBJECTS =  chmod.o

SOURCES =  chmod.c

ALL:		$(MAINS)

chmod:		chmod.o	
	$(CC) $(CFLAGS)  -o chmod  chmod.o $(LDFLAGS) $(PERFLIBS)


chmod.o:	 $(INC)/stdio.h $(INCSYS)/sys/types.h \
		 $(INCSYS)/sys/stat.h $(INCSYS)/sys/dir.h \
		 $(INC)/dirent.h

GLOBALINCS = $(INC)/stdio.h $(INCSYS)/sys/stat.h \
	$(INCSYS)/sys/types.h $(INCSYS)/sys/dir.h \
	$(INC)/dirent.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) -m 0555 -u bin -g bin $(MAINS)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
