#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)libw:libw.mk	1.2.1.1"

#	Makefile for <libw>

ROOT =

USRLIB = $(ROOT)/usr/lib

INC = $(ROOT)/usr/include

INSINC = $(ROOT)/usr/include

INS = install

LDFLAGS =

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.2

MAKEFILE = libw.mk


LIBRARY = libw.a

OBJECTS =  getwidth.o mbftowc.o scrwidth.o wisprint.o

SOURCES =  getwidth.c mbftowc.c scrwidth.c wisprint.c

ALL:		 $(LIBRARY)

$(LIBRARY):	$(LIBRARY)(wisprint.o) $(LIBRARY)(scrwidth.o) \
		$(LIBRARY)(mbftowc.o) $(LIBRARY)(getwidth.o) 


$(LIBRARY)(getwidth.o) getwidth.o:	 $(INC)/ctype.h \
		 $(INC)/stdlib.h libw.h 


$(LIBRARY)(mbftowc.o) mbftowc.o:	 $(INC)/ctype.h \
		 $(INC)/stdlib.h _wchar.h	


$(LIBRARY)(scrwidth.o) scrwidth.o:	 $(INC)/ctype.h \
		 $(INC)/stdlib.h _wchar.h	libw.h 


$(LIBRARY)(wisprint.o) wisprint.o:	 $(INC)/ctype.h \
		 $(INC)/stdlib.h _wchar.h	

GLOBALINCS = $(INC)/ctype.h $(INC)/stdlib.h 

LOCALINCS = _wchar.h libw.h 

clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(LIBRARY)

newmakefile:
	makefile -m -f $(MAKEFILE) -L $(LIBRARY)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(USRLIB) -m 444 -u bin -g bin $(LIBRARY)
	$(INS) -f $(INSINC) -m 444 -u bin -g bin libw.h

size: ALL
	$(SIZE) $(LIBRARY)

strip: ALL

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(USRLIB) | tr ' ' '\012' | sort

product:
	@echo $(LIBRARY)  |  tr ' ' '\012'  | \
	sed 's;^;$(USRLIB)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(LIBRARY)
