#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)news:news.mk	1.6.1.1"

#	Makefile for news

ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(PERFLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = news.mk


MAINS = news

OBJECTS =  news.o

SOURCES =  news.c

ALL:		$(MAINS)

news:		news.o 
	$(CC) $(CFLAGS)  -o news  news.o   $(LDFLAGS)


news.o:	 $(INC)/stdio.h $(INC)/sys/types.h \
		 $(INC)/stdlib.h $(INC)/unistd.h \
		 $(INC)/sys/stat.h $(INC)/setjmp.h \
		 $(INC)/signal.h $(INC)/sys/signal.h \
		 $(INC)/sys/dirent.h $(INC)/pwd.h \
		 $(INC)/time.h

GLOBALINCS = $(INC)/stdio.h $(INC)/sys/types.h \
		 $(INC)/stdlib.h $(INC)/unistd.h \
		 $(INC)/sys/stat.h $(INC)/setjmp.h \
		 $(INC)/signal.h $(INC)/sys/signal.h \
		 $(INC)/sys/dirent.h $(INC)/pwd.h \
		 $(INC)/time.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	install -f $(DIR) -m 00555 -u bin -g bin news

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
