#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)localedef:chrtbl/chrtbl.mk	1.1.3.1"

#	Makefile for chrtbl

ROOT =

INS = install

INSDIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(SHLIBS)

CFLAGS = -O -I$(INC) 

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.1

MAKEFILE = chrtbl.mk


MAINS = chrtbl

OBJECTS =  chrtbl.o

SOURCES =  chrtbl.c

ALL:		$(MAINS)

chrtbl:		chrtbl.o 
	$(CC) $(CFLAGS)  -o chrtbl  chrtbl.o   $(LDFLAGS)


chrtbl.o:	 $(INC)/ctype.h $(INC)/signal.h \
		 $(INC)/stdio.h $(INC)/string.h \
		 $(INC)/sys/signal.h $(INC)/varargs.h 

GLOBALINCS = $(INC)/ctype.h $(INC)/signal.h $(INC)/stdio.h \
	$(INC)/string.h $(INC)/sys/signal.h \
	$(INC)/varargs.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL 
	$(INS) -f  $(INSDIR) $(MAINS) ;\
	$(INS) -f  $(ROOT)/usr/lib/locale/C chrtbl_C ;\
	$(CH)./chrtbl chrtbl_C ;\
	$(CH)$(INS) -f $(ROOT)/usr/lib/locale/C LC_CTYPE ;\
	$(CH)$(INS) -f $(ROOT)/usr/lib/locale/C LC_NUMERIC ;\
	$(CH)rm -f LC_CTYPE LC_NUMERIC

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(INSDIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(INSDIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
