#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#	Portions Copyright (c) 1988, Sun Microsystems, Inc.
#	All Rights Reserved.

#ident	"@(#)chgrp:chgrp.mk	1.4.4.1"

#	Makefile for chgrp

ROOT =

DIR = $(ROOT)/usr/bin

INC = $(ROOT)/usr/include
INCSYS = $(ROOT)/usr/include

LDFLAGS = -s

INS = install

CFLAGS = -O -I$(INC) -I$(INCSYS)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = chgrp.mk


MAINS = chgrp

OBJECTS =  chgrp.o

SOURCES =  chgrp.c

ALL:		$(MAINS)

chgrp:		chgrp.o	
	$(CC) $(CFLAGS)  -o chgrp  chgrp.o $(LDFLAGS) $(SHLIBS)


chgrp.o:	 $(INC)/stdio.h $(INC)/ctype.h \
		 $(INCSYS)/sys/types.h $(INCSYS)/sys/stat.h \
		 $(INC)/grp.h $(INCSYS)/sys/dir.h \
		 $(INC)/dirent.h $(INC)/unistd.h

GLOBALINCS = $(INC)/ctype.h $(INC)/grp.h $(INC)/stdio.h \
	$(INCSYS)/sys/stat.h $(INCSYS)/sys/types.h $(INCSYS)/sys/dir.h \
	$(INC)/dirent.h $(INC)/unistd.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) -m 0555 -u bin -g bin $(MAINS)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
