#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)ogetopt:ogetopt.mk	1.7.1.1"

#	Makefile for getopt

ROOT =

DIR = $(ROOT)/usr/bin

LIBDIR = $(ROOT)/usr/lib

INC = $(ROOT)/usr/include

LDFLAGS = -s $(SHLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

INS = install

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = getopt.mk


MAINS = getopt

LIBMAINS = getoptcvt

OBJECTS =  getopt.o

SOURCES =  getopt.c

ALL:		$(MAINS) $(LIBMAINS)

getopt:	getopt.o 
	$(CC) $(CFLAGS)  -o getopt  getopt.o   $(LDFLAGS)

getoptcvt:
	cp getoptcvt.sh getoptcvt
	$(CH)chmod 777 getoptcvt

getopt.o:	 $(INC)/stdio.h 

GLOBALINCS = $(INC)/stdio.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS) $(LIBMAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) -m 0555 -u bin -g bin $(MAINS)
	$(INS) -f $(LIBDIR) -m 0555 -u bin -g bin $(LIBMAINS)
size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
