#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)wall:wall.mk	1.9.1.1"

#	Makefile for wall 

ROOT =

DIR = $(ROOT)/usr/sbin

SYMLINK = :

INC = $(ROOT)/usr/include

LDFLAGS = -s $(SHLIBS)

CFLAGS = -O -I$(INC)

INS = install

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = wall.mk


MAINS = wall

OBJECTS =  wall.o

SOURCES =  wall.c

ALL:		$(MAINS)

wall:		wall.o 
	$(CC) $(CFLAGS)  -o wall  wall.o   $(LDFLAGS)


wall.o:		 $(INC)/signal.h $(INC)/sys/signal.h \
		 $(INC)/stdio.h $(INC)/grp.h \
		 $(INC)/sys/types.h $(INC)/unistd.h \
		 $(INC)/stdlib.h $(INC)/string.h \
		 $(INC)/sys/stat.h $(INC)/utmp.h \
		 $(INC)/sys/utsname.h $(INC)/sys/dirent.h \
		 $(INC)/pwd.h $(INC)/fcntl.h \
		 $(INC)/time.h $(INC)/errno.h \
		 $(INC)/sys/errno.h 

GLOBALINCS = $(INC)/signal.h $(INC)/sys/signal.h \
		 $(INC)/stdio.h $(INC)/grp.h \
		 $(INC)/sys/types.h $(INC)/unistd.h \
		 $(INC)/stdlib.h $(INC)/string.h \
		 $(INC)/sys/stat.h $(INC)/utmp.h \
		 $(INC)/sys/utsname.h $(INC)/sys/dirent.h \
		 $(INC)/pwd.h $(INC)/fcntl.h \
		 $(INC)/time.h $(INC)/errno.h \
		 $(INC)/sys/errno.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	-rm -f $(ROOT)/etc/wall
	$(INS) -f $(DIR) -m 02555 -u bin -g tty wall
	-$(SYMLINK) /usr/sbin/wall $(ROOT)/etc/wall

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
