#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1988 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)sdb:libint/i386/makefile	1.2"

TARGET = $(PRODLIB)/libint.a

include ../../util/std.make

CCSOURCES = \
	$(COMMON)/Interface.C \
	$(COMMON)/SrcFile.C \
	$(COMMON)/printx.C

include DEPEND

include ../../util/lib.make
