#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.


#ident	"@(#)uname:uname.mk	1.4.6.1"


#		PROPRIETARY NOTICE (Combined)
#
#This source code is unpublished proprietary information
#constituting, or derived under license from AT&T's UNIX(r) System V.
#In addition, portions of such source code were derived from Berkeley
#4.3 BSD under license from the Regents of the University of
#California.
#
#
#
#		Copyright Notice 
#
#Notice of copyright on this source code product does not indicate 
#publication.
#
#	(c) 1986,1987,1988,1989  Sun Microsystems, Inc
#	(c) 1983,1984,1985,1986,1987,1988,1989  AT&T.
#	          All rights reserved.

#	Makefile for uname 

ROOT =

DIR = $(ROOT)/usr/bin

DIR2 = $(ROOT)/sbin

INC = $(ROOT)/usr/include

LDFLAGS = -s 

CFLAGS = -O -I$(INC)

INS = install

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = uname.mk

MAINS = uname

OBJECTS =  uname.o

SOURCES =  uname.c

ALL:		$(MAINS)

uname:	uname.o
	$(CC) $(CFLAGS) -o uname uname.o $(LDFLAGS) $(ROOTLIBS)

uname.o:	 $(INC)/stdio.h \
		 $(INC)/sys/utsname.h \
		 $(INC)/sys/systeminfo.h \
		 $(INC)/string.h	\
		 $(INC)/sys/types.h \
		 $(INC)/sys/fcntl.h \
		 $(INC)/sys/stat.h \
		 $(INC)/sys/sysi86.h 

GLOBALINCS = $(INC)/stdio.h \
	$(INC)/string.h \
	$(INC)/sys/sysi86.h \
	$(INC)/sys/fcntl.h \
	$(INC)/sys/types.h \
	$(INC)/sys/utsname.h \
	$(INC)/sys/systeminfo.h


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	$(INS) -f $(DIR) -m 0555 -u bin -g bin $(MAINS)
	$(INS) -f $(DIR2) -m 0555 -u bin -g bin $(MAINS)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
