#	Copyright (c) 1990 UNIX System Laboratories, Inc.
#	Copyright (c) 1984, 1986, 1987, 1988, 1989, 1990 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF
#	UNIX System Laboratories, Inc.
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)oamintf:devices/remove/Makefile	1.5.2.2"

O_DFILES=\
	Help \
	Menu.remove Form.remove Text.err Text.remove Text.rmnok Text.rmok

all:

clean:

clobber: clean
	:

size strip: all
	:

install: all xinstall

PROTO=Prototype
OBJECTS=$(O_DFILES)
include ../../Install
